# Generated by Django 5.1.2 on 2024-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kwh_usage', models.FloatField()),
                ('ng_usage', models.FloatField()),
                ('gasoline_usage', models.FloatField()),
                ('diesel_usage', models.FloatField()),
                ('total_emission', models.FloatField()),
            ],
        ),
    ]
